# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations

changelog:

  exclude:

    labels:
      - 'Release process'
      - 'ci:no-build'
      
  categories:

    - title: 'API Changes'
      labels:
        - 'API Change'

    - title: 'UI Changes'
      labels:
        - 'UI'
        - 'Look and Feel'

    - title: 'Gradle'
      labels:
        - 'Gradle'

    - title: 'Maven'
      labels:
        - 'Maven'

    - title: 'Java'
      labels:
        - 'Java'

    - title: 'PHP'
      labels:
        - 'PHP'

    - title: 'C/C++'
      labels:
        - 'C/C++'

    - title: 'Enterprise'
      labels:
        - 'enterprise'
        - 'Java EE/Jakarta EE'
        - 'Micronaut'
        - 'Payara'

    - title: 'Web'
      labels:
        - 'JavaScript'
        - 'TypeScript'
        - 'HTML'

    - title: 'Platform'
      labels:
        - 'Platform'

    - title: 'Maintanance'
      labels:
        - 'Code cleanup'
        - 'Upgrade Library'
      
    - title: Other Changes
      labels:
        - "*"
