# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
language: java
dist: bionic
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - xvfb
      - openjfx
      - libgfortran3
      - libxml2-utils

install:
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/nbbuild/travis"
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

cache:
  directories:
  - $HOME/.hgexternalcache

git:
  quiet: true
  depth: 50

matrix:
    include:
        - name: Pristine platform build
          jdk: openjdk8
          env:
            - ANT_OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
          script:
            - nbbuild/travis/ant.sh -quiet build-source-config -Dcluster.config=platform
            - mkdir tmpplatform
            - cd tmpplatform
            - unzip -qq ../nbbuild/build/platform-src*
            - chmod a+x nbbuild/travis/ant.sh
            - nbbuild/travis/ant.sh build -Dcluster.config=platform

        - name: Compile all modules & tests
          jdk: openjdk8
          env:
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=full -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
          script:
            - nbbuild/travis/ant.sh $OPTS build
            - nbbuild/travis/ant.sh $OPTS test -Dtest.includes=NoTestsJustBuild

        - name: Test nb modules
          jdk: openjdk8
          env:
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=minimal -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false -Dtest-unit-sys-prop.ignore.random.failures=true"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - ant $OPTS -f nb/deadlock.detector test
            - ant $OPTS -f nb/ide.branding test
            - ant $OPTS -f nb/o.n.upgrader test
            #- ant $OPTS -f nb/updatecenters test
            - ant $OPTS -f nb/welcome test

        - name: "Versioning modules (ide/versioning and ide/versioning.core) tests"
          jdk: openjdk8
          env:
              - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=minimal -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
              - OPTS_TEST="-Dtest-unit-sys-prop.ignore.random.failures=true -Dvanilla.javac.exists=true"
              - GIT_TEST_REPO="$HOME/git_test_repo"
          script:
              # Build sources
              - nbbuild/travis/ant.sh $OPTS clean
              - nbbuild/travis/ant.sh $OPTS build
              # Run unit tests
              - ant $OPTS $OPTS_TEST -f ide/versioning.core test-unit
              - ant $OPTS $OPTS_TEST -f ide/versioning test-unit
              #Prepare git repo for tests
              - git init $GIT_TEST_REPO
              # Prepare config file for ide/versioning.core module
              - touch ide/versioning.core/test/qa-functional/data/tck.properties
              - echo "test.root = $GIT_TEST_REPO" > ide/versioning.core/test/qa-functional/data/tck.properties
              - echo "test.vcs = org.netbeans.modules.versioning.DelegatingVCS" >> ide/versioning.core/test/qa-functional/data/tck.properties
              # Run functional tests for ide/versioning.core module
              - ant $OPTS $OPTS_TEST -f ide/versioning.core test-qa-functional
              # Prepare config file for ide/versioning module
              - touch ide/versioning/test/qa-functional/data/tck.properties
              - echo "test.root = $GIT_TEST_REPO" > ide/versioning/test/qa-functional/data/tck.properties
              - echo "test.vcs = org.netbeans.modules.git.GitVCS" >> ide/versioning/test/qa-functional/data/tck.properties
              # Run functional tests for ide/versioning module
              - ant $OPTS $OPTS_TEST -f ide/versioning test-qa-functional

        - name: "Tests with mysql database"
          jdk: openjdk8
          services:
            - mysql
          env:
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -Dcluster.config=minimal -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
            - OPTS_TEST="-Dtest-unit-sys-prop.ignore.random.failures=true -Dvanilla.javac.exists=true -Dtest-unit-sys-prop.mysql.user=root -Dtest-unit-sys-prop.mysql.password=password"
          before_script:
            - echo "ALTER USER root@'localhost' IDENTIFIED BY 'password';\nFLUSH PRIVILEGES;\n" | mysql -u root
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - travis_retry ant $OPTS $OPTS_TEST -f ide/db.metadata.model test
            - travis_retry ant $OPTS $OPTS_TEST -f ide/db.mysql test

        - name: Build the Visual Studio Code extension for Java
          jdk: openjdk8
          before_install:
            - nvm install 16.13.2
          env:
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=release -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false -Dtest-unit-sys-prop.ignore.random.failures=true"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - (cd java/java.lsp.server; ant build-vscode-ext -D3rdparty.modules=.*externalcodeformatter.*)
            - (cd java/java.lsp.server; ant test-vscode-ext)

        - name: "GraalVM Tests (latest)"
          jdk: openjdk8
          env:
            - GRAAL_VERSION="21.1.0"
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=release -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - travis_wait nbbuild/travis/scripting.sh

        - name: "GraalVM Tests (LTS)"
          jdk: openjdk8
          env:
            - GRAAL_VERSION="20.3.0"
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=release -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - travis_wait nbbuild/travis/scripting.sh

#   exile: for tests which don't behave. Job should be kept short to be easily restartable
        - name: Test unreliable tests on Java 8
          jdk: openjdk8
          env:
            - OPTS="-Dmetabuild.jsonurl=https://raw.githubusercontent.com/apache/netbeans-jenkins-lib/master/meta/netbeansrelease.json -quiet -Dcluster.config=java -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false -Dtest-unit-sys-prop.ignore.random.failures=true"
          before_script:
            - nbbuild/travis/ant.sh $OPTS clean
            - nbbuild/travis/ant.sh $OPTS build
          script:
            - travis_retry ant $OPTS -f java/java.lsp.server test

after_failure:
  - nbbuild/travis/print-junit-report.sh
  - sleep 3
